---
- name: Ensure the Python 3 development system package is installed
  become: true
  ansible.builtin.package:
    name: python3-dev
    state: present

- name: Ensure application files are present in /opt
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('env', 'PWD') }}/src/"
    dest: /opt/ntag-pi/
    mode: preserve
  notify:
    - Restart application service

- name: Ensure the wheels package is installed in the virtual environment
  become: true
  ansible.builtin.pip:
    virtualenv: /opt/ntag-pi/venv
    virtualenv_command: /usr/bin/python3 -m venv
    name: wheel

- name: Ensure the virtual environment is populated with application requirements
  become: true
  ansible.builtin.pip:
    virtualenv: /opt/ntag-pi/venv
    virtualenv_command: /usr/bin/python3 -m venv
    requirements: /opt/ntag-pi/requirements.txt
  notify:
    - Restart application service

- name: Ensure the application systemd unit is present
  become: true
  ansible.builtin.copy:
    src: ntag-pi.service
    dest: /etc/systemd/system/
    mode: preserve
  notify:
    - Restart application service

- name: Ensure the application service is running
  become: true
  ansible.builtin.systemd:
    name: ntag-pi
    state: started
    enabled: true
    daemon_reload: true
...
